### ISSUE TITLE
How to use msdf fonts?

### ISSUE THREAD

**Issue by PainKKKiller** [PixelsCommander/pixi-sdf-text#7]
Just playing with you demo tried to change fonts in it. Did it in this way: 

```
var style = {
        fontSize: 12,
        fontWeight: 'bold',
        fill: 0x39FF14,
        align: 'left',
        wordWrapWidth: 400,
        lineHeight: 64,
        fontURL: 'assets/Roboto-msdf.json',
        imageURL: 'assets/Roboto-msdf.png'
    };

    window.text = new PIXI.sdf.Text('This is a multiline SDF text', style);
```
And I got blurry text. So how to use this kind of fonts?
![screenshot from 2017-03-31 19-49-45](https://cloud.githubusercontent.com/assets/5506725/24560526/d24e33fc-164b-11e7-895a-dc06380aee25.png)

**Comment by PixelsCommander** [comment]
There is TBD #4 to fix this. You may keep track of this issue by watching repository
